GRID_WIDTH = 8
GRID_HEIGHT = 8
TILE_SIZE = 64
SCREEN_WIDTH = GRID_WIDTH * TILE_SIZE
SCREEN_HEIGHT = GRID_HEIGHT * TILE_SIZE
UI_PANEL = (GRID_WIDTH * TILE_SIZE) * .35
GRAY = (15, 15, 15)

MODE = 0

#strings
STRUCTURES = "structures"
ENEMIES = "enemies"
PROJECTILES = "projectiles"